### ISSUE TITLE
티어 오류

### ISSUE THREAD

**Issue by asu1493** [webgori/lolien-discord-bot#10]
소환사이름 shee
티어가 골드4로 뜨네요
현재 검색결과 골드1입니다

1팀: kky0303(PLATINUM-II / 18), 괘미개미(GOLD-IV / 12), 끼룩꽁깽(GOLD-IV / 12), 한오백년(SILVER-II / 10), 미드솔킬정글차이(GOLD-III / 13)
2팀: Lain(PLATINUM-II / 18), 아미스시마(SILVER-III / 9), JRabbit(GOLD-IV / 12), shee(GOLD-IV / 12), 태랑하마(PLATINUM-III / 17)

**Comment by webgori** [comment]
최초 소환사 등록 기준 티어를 보여주고 있네요.
새벽에 스케줄링하여 갱신되게끔 작업 하겠습니다.

**Comment by webgori** [comment]
수정했습니다.
