### ISSUE TITLE
!팀구성 밸런스 추가 기능

### ISSUE THREAD

**Issue by KURIKAME** [webgori/lolien-discord-bot#20]
기존

!팀구성 밸런스 AAA,BBB,CCC,DDD,EEE,FFF,GGG,HHH,III,JJJ

결과 
LoLienBot : 
1팀 : AAA(티어 점수), BBB(티어 점수), CCC(티어 점수), DDD(티어 점수), EEE(티어 점수)

2팀 : FFF(티어 점수), GGG(티어 점수), HHH(티어 점수), III(티어 점수), JJJ(티어 점수)

추가

!팀구성 밸런스 AAA,BBB,CCC,DDD,EEE,FFF,GGG,HHH,III,JJJ

결과 

LoLienBot : 
1팀 : AAA(티어 점수), BBB(티어 점수), CCC(티어 점수), DDD(티어 점수), EEE(티어 점수)
LoLienBot : 
2팀 : FFF(티어 점수), GGG(티어 점수), HHH(티어 점수), III(티어 점수), JJJ(티어 점수)

> 1,2팀 명단을 한꺼번 말하면 복붙 롤클라채팅에다 넣어보면 글자가 짤리는 경우가 가끔 생김
> 1팀,2팀 나눠서 말하면 어떨까 합니다.
> 다 말하면, 바로 각팀 모스트3개씩 소개에도 말합니다.
> 모스트3 추천이유, 1팀,2팀 대표가 무얼 밴해야하는지 바로 참고 하라는 의미

LoLienBot : 
1팀
AAA (모스트 3)  (예: KURIKAME 갈리오 모르가나 애쉬)
BBB (모스트 3)
CCC (모스트 3)
DDD (모스트 3)
EEE (모스트 3)

2팀
FFF (모스트 3)
GGG (모스트 3)
HHH (모스트 3)
III (모스트 3)
JJJ (모스트 3)

**Comment by webgori** [comment]
@KURIKAME 
알고계실지 모르겠지만 1,2팀 명단이 한번에 보이는건 Discord 프로그램에서 처음 문장과 다음 문장 사이의 입력 시간이 정해진 기준 시간 (예를들어서 1초) 보다 적을경우 한번에 말하는걸로 보이게 되어 있습니다.

해결 방법으로는 1팀 말하게 하고, 딜레이를 3초 정도 주고 2팀 말하게 하고 이런 방법이 있는데... 좋은 방법은 아니네요.

> 다 말하면, 바로 각팀 모스트3개씩 소개에도 말합니다.
모스트3 추천이유, 1팀,2팀 대표가 무얼 밴해야하는지 바로 참고 하라는 의미

이 부분은 이해가 잘 안가네요...

```
LoLienBot :
1팀
AAA (모스트 3) (예: KURIKAME 갈리오 모르가나 애쉬)
BBB (모스트 3)
CCC (모스트 3)
DDD (모스트 3)
EEE (모스트 3)

2팀
FFF (모스트 3)
GGG (모스트 3)
HHH (모스트 3)
III (모스트 3)
JJJ (모스트 3)
```

예시로 들어준 부분은 이해 했씁니다.
예시와 같이 하면 될까요?

**Comment by KURIKAME** [comment]
아 그러면, 1,2팀 명단이 한번에 보여주는식으로 말하고 
딜레이를 3초 정도 주고 예시와 같이 보여주면 될것 같습니다.

(설명내용은 부족했네요.
그니깐.. 1,2팀 각대표가 상대팀 누굴, 어떤챔피언을 저격밴 해야하는지
상의 해야하는데, 팀원 모스트 3개씩 소개 나열되면 한눈에 바로 확인해서 상의하라는 편의성예요)

**Comment by KURIKAME** [comment]
명령어 

> !팀구성 밸런스 AAA,BBB,CCC,DDD,EEE,FFF,GGG,HHH,III,JJJ

결과

> LoLienBot :
> 1팀 : AAA(티어 점수), BBB(티어 점수), CCC(티어 점수), DDD(티어 점수), EEE(티어 점수)
> LoLienBot :
> 2팀 : FFF(티어 점수), GGG(티어 점수), HHH(티어 점수), III(티어 점수), JJJ(티어 점수)

3초 딜레이 후

> LoLienBot :
> 1팀
> AAA (나서스, 잭스, 이렐리아)
> BBB (이블린, 리신, 세주아니)
> CCC (제드, 카타리나, 빅토르)
> DDD (애쉬, 루시안, 진)
> EEE (쓰레쉬, 알리, 블츠)
> 
> 2팀
> FFF (나서스, 잭스, 이렐리아)
> GGG (이블린, 리신, 세주아니)
> HHH (제드, 카타리나, 빅토르)
> III (애쉬, 루시안, 진)
> JJJ (쓰레쉬, 알리, 블츠)

**Comment by KURIKAME** [comment]
> @KURIKAME
> 설명해주신 부분에 기존에 있던 티어와 가중치는 없는 것 같은데요.
> 제거하고 모스트 챔프만 보이면 되는건가요?

명령어

`!팀구성 밸런스 AAA,BBB,CCC,DDD,EEE,FFF,GGG,HHH,III,JJJ`

결과

```
LoLienBot :
1팀 : AAA(티어 점수), BBB(티어 점수), CCC(티어 점수), DDD(티어 점수), EEE(티어 점수)
LoLienBot :
2팀 : FFF(티어 점수), GGG(티어 점수), HHH(티어 점수), III(티어 점수), JJJ(티어 점수)
```

3초 딜레이 후

```
LoLienBot :
1팀
AAA (나서스, 잭스, 이렐리아)
BBB (이블린, 리신, 세주아니)
CCC (제드, 카타리나, 빅토르)
DDD (애쉬, 루시안, 진)
EEE (쓰레쉬, 알리, 블츠)

2팀
FFF (나서스, 잭스, 이렐리아)
GGG (이블린, 리신, 세주아니)
HHH (제드, 카타리나, 빅토르)
III (애쉬, 루시안, 진)
JJJ (쓰레쉬, 알리, 블츠)
```

**Comment by webgori** [comment]
@KURIKAME 
적용했습니다. 확인 후 이상 있으시면 댓글 남겨주세요.

**Comment by KURIKAME** [comment]
넵 아주 좋습니다 좋아요
