### ISSUE TITLE
내전 결과등록시 질문입니다.

### ISSUE THREAD

**Issue by kioo381** [webgori/lolien-discord-bot#6]
내전결과 등록할 때 사용자명 순서를 입장팀순서부터 입력하라고 하셨는데요, 클라이언트에서 확인한순서가 맞을까요? 사용자대전 기록을 확인하면 항상 제 아이디가 1번에있어서요

**Comment by webgori** [comment]
클라이언트에서 확인한 순서로 해주시면 됩니다!

**Comment by kioo381** [comment]
ㅠㅜ 제가벤픽을 안했기에 1픽이아닌게 확실한데..... 클라에는전부 1픽으로나와요!

**Comment by kioo381** [comment]
사용자설정했던 게임들 URL 들어가서 확인해보니 URL 타고들어가서 나오는 픽순이 맞는거같아요! 클라에서는 무조건 자기가 1픽 으로나오는거같아요

**Comment by webgori** [comment]
커뮤니케이션 미스가 있었던 것 같습니다.
제가 말씀드린 클라이언트 상이라는건 아래 사진을 말씀드린거고요.
![image](https://user-images.githubusercontent.com/5680005/56486673-641e4480-6513-11e9-934f-4cd2a4a8f1f4.png)
@kioo381 님이 말씀하신 클라이언트상은 대전 기록을 말씀하신 것 같습니다.
대전 기록에서는 자신이 항상 1픽으로 나오는게 맞고요, 항상 1픽으로 나오기 때문에 게임 시작 전의 순서를 기억했다가 따로 적어주셔야 합니다.

**Comment by kioo381** [comment]
ㅠㅜ 게임시작전의 순서를모르면 등록할방법이없나요

**Comment by webgori** [comment]
지금으로서는 같이 게임했던 팀원들과 순서 비교해서 맞춰보는 방법밖에 없습니다 :(

**Comment by kioo381** [comment]
넵 고생이많으셔요 재능기부 감쟈합니다 :)
